'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),C=require('../tv/core');
let id=0;function cmd(s,action,value,now=1000){return C.apply(s,{id:String(++id),revision:s.revision,notAfter:now+100,action,value},now);}
test('start, pause, add time, reset and roster',()=>{const s=C.fresh();cmd(s,'start');assert.equal(C.remaining(s,11000),1190000);cmd(s,'pause',null,11000);assert.equal(C.remaining(s,50000),1190000);cmd(s,'time',60000);assert.equal(s.remaining,1250000);cmd(s,'players',9);assert.equal(s.players,9);cmd(s,'name','决赛');assert.equal(s.name,'决赛');cmd(s,'reset');assert.equal(s.remaining,1200000);assert.equal(s.running,false);});
test('reload restores elapsed time and multiple missed levels',()=>{const s=C.fresh();cmd(s,'start');const r=C.restore(JSON.stringify(s),2501000);assert.equal(r.level,2);assert.equal(C.remaining(r,2501000),1100000);assert.equal(r.revision,3);});
test('paused restore does not consume elapsed time; corrupt state resets safely',()=>{const s=C.fresh();assert.equal(C.restore(JSON.stringify(s),9e9).remaining,1200000);assert.deepEqual(C.restore('{',0),C.fresh());});
test('duplicate, stale and expired commands rejected including after reload',()=>{let s=C.fresh();const c={id:'abc',revision:0,action:'time',value:60000,notAfter:2000};assert.equal(C.apply(s,c,1000),'applied');s=C.restore(JSON.stringify(s),1100);assert.equal(C.apply(s,c,1100),'duplicate');assert.equal(C.apply(s,{...c,id:'new'},1100),'stale');assert.equal(C.apply(s,{...c,id:'old'},3000),'expired');assert.equal(s.remaining,1260000);});
test('automatic progression stops at final level and bounds are validated',()=>{const s=C.fresh();cmd(s,'start');C.tick(s,20000000);assert.equal(s.level,11);assert.equal(s.running,false);assert.equal(s.remaining,0);assert.equal(cmd(s,'players',-1),'invalid');assert.equal(cmd(s,'time',123),'invalid');assert.equal(cmd(s,'start'),'finished');});
test('phone-created tournament replaces full plan and starts atomically',()=>{const s=C.fresh();const draft={name:'家庭决赛',players:8,plan:[{small:25,big:50,ante:0,minutes:10},{small:50,big:100,ante:100,minutes:15}]};assert.equal(cmd(s,'tournament',draft),'applied');assert.equal(s.name,'家庭决赛');assert.equal(s.players,8);assert.equal(s.running,true);assert.equal(s.remaining,600000);draft.plan[0].small=999;assert.equal(s.plan[0].small,25);const restored=C.restore(JSON.stringify(s),601000);assert.equal(restored.level,1);assert.equal(C.remaining(restored,601000),900000);assert.equal(C.snapshot(restored,601000).levelCount,2);cmd(restored,'reset');assert.equal(restored.remaining,900000);assert.equal(restored.running,false);});
test('invalid tournament leaves current game unchanged',()=>{const s=C.fresh(),before=JSON.stringify(s);for(const plan of [[],[{small:200,big:100,ante:0,minutes:20}],[{small:50,big:100,ante:0,minutes:0}]])assert.equal(cmd(s,'tournament',{name:'test',players:8,plan}),'invalid');assert.equal(JSON.stringify(s),before);});
test('old saved games migrate and duplicate tournament cannot restart timer',()=>{const old=C.fresh();delete old.plan;assert.equal(C.restore(JSON.stringify(old),1000).plan.length,12);const s=C.fresh(),c={id:'create',revision:0,notAfter:9000,action:'tournament',value:{name:'赛',players:6,plan:[{small:10,big:20,ante:0,minutes:1}]}};assert.equal(C.apply(s,c,1000),'applied');assert.equal(C.apply(s,c,8000),'duplicate');assert.equal(C.remaining(s,8000),53000);});
